excluded:
  - Pods
  - PrivatePods
  - R.generated.swift
  - novawalletTests
  - novawalletIntegrationTests
  - NovaPushNotificationServiceExtension/R.generated.swift
identifier_name:
  excluded:
    - id
nesting:
  type_level: 3
  statement_level: 3
