disabled_rules:
  - switch_case_alignment
excluded:
  - R.generated.swift
  - novawalletTests
  - novawalletIntegrationTests
  - NovaPushNotificationServiceExtension/R.generated.swift
  - vendor/bundle
identifier_name:
  excluded:
    - id
nesting:
  type_level: 3
  statement_level: 3
large_tuple:
  warning: 6
  error: 7
type_body_length:
  warning: 400
  error: 500
