[modules.NovaModules]

imports = ["Foundation", "Foundation_iOS", "Keystore_iOS", "SubstrateSdk",]

testableImports = ["novawallet"]

sources = [
    "novawalletTests/Mocks/TestSecretStoreManager.swift",
    "novawallet/Common/Helpers/Scheduler.swift",
    "novawallet/Common/LocalAuthentication/BiometryAuth.swift",
    "novawallet/Common/EventCenter/EventProtocols.swift",
    "novawallet/Common/Network/Misc/SubstrateOperationFactory.swift",
    "novawallet/Common/Helpers/AccountRepositoryFactory.swift",
    "novawallet/Common/Operation/EraCountdownOperationFactory/EraCountdownOperationFactory.swift",
    "novawallet/Common/Network/JSONRPC/ConnectionAutobalancing.swift",
    "novawallet/Common/Network/JSONRPC/ConnectionStateReporting.swift",
    "novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionFactory.swift",
    "novawallet/Common/Network/Misc/DataOperationFactory.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeFilesOperationFactory.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProviderPool.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProviderFactory.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeCodingService.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSyncService.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/CommonTypesSyncService.swift",
    "novawallet/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProvider.swift",
    "novawallet/Common/Services/ChainRegistry/ConnectionPool/ConnectionPool.swift",
    "novawallet/Common/Services/ChainRegistry/SpecVersionSubscriptionFactory.swift",
    "novawallet/Common/Services/ChainRegistry/SpecVersionSubscription.swift",
    "novawallet/Common/Services/ChainRegistry/ChainRegistry.swift",
    "novawallet/Common/Services/RemoteSubscription/Substrate/CrowdloanRemoteSubscriptionService.swift",
    "novawallet/Common/Services/RemoteSubscription/Substrate/StakingRemoteSubscriptionService.swift",
    "novawallet/Common/Services/RemoteSubscription/Substrate/StakingAccountUpdatingService.swift",
    "novawallet/Modules/Staking/Services/StakingServiceFactory.swift",
    "novawallet/Common/Currency/CurrencyRepository.swift",
    "novawallet/Common/Services/ApplicationService.swift",
    "novawallet/Common/Protocols/LoadableViewProtocol.swift",
    "novawallet/Common/Protocols/ControllerBackedProtocol.swift",
    "novawallet/Common/Protocols/WebPresentable.swift",
    "novawallet/Common/Protocols/AlertPresentable.swift",
    "novawallet/Common/Protocols/ModalAlertPresenting.swift",
    "novawallet/Common/Protocols/ExtrinsicSubmissionPresentation/ExtrinsicSubmissionPresenting.swift",
    "novawallet/Common/Protocols/SharingPresentable.swift",
    "novawallet/Common/Protocols/AccountSelectionPresentable.swift",
    "novawallet/Common/Protocols/AuthorizationPresentable.swift",
    "novawallet/Common/ViewController/SearchController/TableSearchProtocols.swift",
    "novawallet/Common/Protocols/WalletSwitchPresentable.swift",
    "novawallet/Common/Services/Web3AlertService/PushNotificationsServiceFacade.swift",
    "novawallet/Common/Services/RemoteSubscription/Substrate/StakingRemoteSubscriptionProtocols.swift",
    "novawallet/Common/Currency/CurrencyRepositoryProtocol.swift",
    "novawallet/Common/Storage/WalletStorageCleaning/WalletStorageCleaning.swift",
    "novawallet/Common/Network/IPAddressProvider/IPAddressProvider.swift",
    "novawallet/Common/RampProvider/Providers/Helpers/MerchantTransactionIdFactory.swift",
    "novawallet/Modules/Root/RootProtocol.swift",
    "novawallet/Modules/Onboarding/UsernameSetup/UsernameSetupProtocols.swift",
    "novawallet/Modules/Onboarding/Start/OnboardingMainProtocol.swift",
    "novawallet/Modules/Onboarding/AccountCreate/AccountCreateProtocols.swift",
    "novawallet/Modules/ImportWallet/AccountImport/AccountImportProtocols.swift",
    "novawallet/Modules/Onboarding/AccountConfirm/AccountConfirmProtocols.swift",
    "novawallet/Modules/Pincode/PinSetup/PinSetupProtocol.swift",
    "novawallet/Modules/Settings/SettingsProtocols.swift",
    "novawallet/Modules/ManageWallets/AccountManagement/AccountManagementProtocols.swift",
    "novawallet/Modules/AccountInfo/AccountInfoProtocols.swift",
    "novawallet/Modules/NetworkManagement/NetworkManagementProtocols.swift",
    "novawallet/Modules/NetworkInfo/NetworkInfoProtocols.swift",
    "novawallet/Modules/AddConnection/AddConnectionProtocols.swift",
    "novawallet/Modules/ExportWallet/AccountExportPassword/AccountExportPasswordProtocols.swift",
    "novawallet/Modules/ExportWallet/ExportGenericView/ExportGenericProtocols.swift",
    "novawallet/Modules/ExportWallet/ExportMnemonic/ExportMnemonicProtocols.swift",
    "novawallet/Modules/ExportWallet/ExportRestoreJson/ExportRestoreJsonProtocols.swift",
    "novawallet/Modules/TransactionHistory/HistoryFilter/WalletHistoryFilterProtocols.swift",
    "novawallet/Modules/Staking/Operations/ValidatorOperationFactory/ValidatorOperationFactoryProtocol.swift",
    "novawallet/Modules/Staking/StakingMain/StakingMainProtocols.swift",
    "novawallet/Modules/Staking/StakingMain/Relaychain/StakingRelaychainProtocols.swift",
    "novawallet/Modules/Staking/Operations/NetworkStakingInfoOperationFactory.swift",
    "novawallet/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationProtocols.swift",
    "novawallet/Modules/Staking/StakingRewardDetails/StakingRewardDetailsProtocols.swift",
    "novawallet/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsProtocols.swift",
    "novawallet/Modules/Staking/StakingBalance/StakingBalanceProtocols.swift",
    "novawallet/Modules/Staking/StakingUnbondSetup/StakingUnbondSetupProtocols.swift",
    "novawallet/Modules/Staking/StakingUnbondConfirm/StakingUnbondConfirmProtocols.swift",
    "novawallet/Modules/Staking/StakingRedeem/StakingRedeemProtocols.swift",
    "novawallet/Modules/Staking/StakingBondMore/StakingBondMoreProtocols.swift",
    "novawallet/Modules/Staking/StakingBondMoreConfirmation/StakingBondMoreConfirmationProtocols.swift",
    "novawallet/Modules/Staking/StakingRebondSetup/StakingRebondSetupProtocols.swift",
    "novawallet/Modules/Staking/StakingRebondConfirmation/StakingRebondConfirmationProtocols.swift",
    "novawallet/Modules/Staking/ControllerAccount/ControllerAccountProtocols.swift",
    "novawallet/Modules/Staking/StakingRewardDestinationSetup/StakingRewardDestSetupProtocols.swift",
    "novawallet/Modules/Staking/StakingRewardDestConfirm/StakingRewardDestConfirmProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/SelectValidatorsStart/SelectValidatorsStartProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/YourValidatorList/YourValidatorListProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/ValidatorListFilter/ValidatorListFilterProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/ValidatorSearch/ValidatorSearchProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/SelectValidatorsConfirmProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/RecommendedValidatorList/RecommendedValidatorListProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/SelectedValidatorList/SelectedValidatorListProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/CustomValidatorList/CustomValidatorListProtocols.swift",
    "novawallet/Modules/Staking/SelectValidatorsFlow/ValidatorInfo/ValidatorInfoProtocols.swift",
    "novawallet/Modules/Vote/Crowdloan/CrowdloanList/CrowdloanListProtocols.swift",
    "novawallet/Modules/Vote/Crowdloan/CrowdloanContribution/CrowdloanContributionProtocols.swift",
    "novawallet/Modules/Vote/Crowdloan/CrowdloanContributionSetup/CrowdloanContributionSetupProtocols.swift",
    "novawallet/Modules/Vote/Crowdloan/CrowdloanContributionConfirm/CrowdloanContributionConfirmProtocols.swift",
    "novawallet/Modules/Vote/Crowdloan/CustomCrowdloan/CustomCrowdloanDelegate.swift",
    "novawallet/Modules/Vote/Crowdloan/ReferralCrowdloan/ReferralCrowdloanProtocols.swift",
    "novawallet/Common/ViewController/SelectionListViewController/SelectionListProtocols.swift",
    "novawallet/Modules/ChainAssetSelection/ChainAssetSelectionProtocols.swift",
    "novawallet/Modules/ImportWallet/AdvancedWallet/AdvancedWalletProtocols.swift",
    "novawallet/Modules/DApp/DAppAuthConfirm/DAppAuthConfirmProtocols.swift",
    "novawallet/Modules/DApp/DAppList/DAppListProtocols.swift",
    "novawallet/Modules/DApp/DAppBrowser/DAppBrowserProtocols.swift",
    "novawallet/Modules/DApp/DAppOperationConfirm/DAppOperationConfirmProtocols.swift",
    "novawallet/Modules/DApp/DAppSearch/DAppSearchProtocols.swift",
    "novawallet/Modules/AssetsSettings/AssetsSettingsProtocols.swift",
    "novawallet/Modules/OperationDetails/OperationDetailsProtocols.swift",
    "novawallet/Modules/Vote/Crowdloan/CrowdloanYourContributions/CrowdloanYourContributionsProtocols.swift",
    "novawallet/Modules/SecurityLayer/SecurityLayerProtocols.swift",
    "novawallet/Modules/DApp/WalletConnect/Service/WalletConnectProtocols.swift",
    "novawallet/Modules/ManualBackup/BackupAttention/CheckboxListPresenter/CheckboxListPresenterTrait.swift",
    "novawallet/Modules/TokensManage/List/TokensManageProtocols.swift",
]

exclude = [
"RootPresenterFactoryProtocol", "UsernameSetupViewFactoryProtocol", "OnboardingMainViewFactoryProtocol", "AccountCreateViewFactoryProtocol", "AccountImportViewFactoryProtocol", "AccountConfirmViewFactoryProtocol", "PinViewFactoryProtocol", "ProfileViewFactoryProtocol", "AccountManagementViewFactoryProtocol", "AccountInfoViewFactoryProtocol", "NetworkManagementViewFactoryProtocol", "NetworkInfoViewFactoryProtocol", "AddConnectionViewFactoryProtocol", "AccountExportPasswordViewFactoryProtocol", "ExportRestoreJsonViewFactoryProtocol", "ExportMnemonicViewFactoryProtocol", "StakingMainViewFactoryProtocol", "SelectValidatorsStartViewFactoryProtocol", "SelectValidatorsConfirmViewFactoryProtocol", "RecommendedValidatorListViewFactoryProtocol", "SelectedValidatorListViewFactoryProtocol", "CustomValidatorListViewFactoryProtocol", "ValidatorInfoViewFactoryProtocol", "WalletHistoryFilterViewFactoryProtocol", "StakingPayoutConfirmationViewFactoryProtocol", "StakingRewardDetailsViewFactoryProtocol", "StakingRewardPayoutsViewFactoryProtocol", "StakingPayoutConfirmViewModelFactoryProtocol", "YourValidatorListViewFactoryProtocol", "StakingUnbondSetupViewFactoryProtocol", "StakingUnbondConfirmViewFactoryProtocol", "StakingRedeemViewFactoryProtocol", "StakingBondMoreViewFactoryProtocol", "StakingRebondSetupViewFactoryProtocol", "ValidatorListFilterViewFactoryProtocol", "ValidatorSearchViewFactoryProtocol", "JSONRPCBatchHandler"
]