import UIKit
import Operation_iOS
import BigInt

final class NominationPoolBondMoreSetupInteractor: NominationPoolBondMoreBaseInteractor {}

extension NominationPoolBondMoreSetupInteractor: NominationPoolBondMoreSetupInteractorInputProtocol {}
