import UIKit
import RobinHood
import BigInt

final class NominationPoolBondMoreSetupInteractor: NominationPoolBondMoreBaseInteractor {}

extension NominationPoolBondMoreSetupInteractor: NominationPoolBondMoreSetupInteractorInputProtocol {}
