opt_out_usage
default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

platform :ios do
  # imports
  import ("lines/line_build.rb")
  import ("lines/line_tests.rb")
  import ("lines/line_firebase_distribute.rb")
  import ("lines/line_register_device.rb")
  import ("lines/line_testflight.rb")
  import ("lines/line_signing.rb")

  # shared variables
  main_target = "novawallet"
  main_scheme = "novawallet"
  main_configuration = "Debug"

  test_scheme = "novawallet"

  testflight_distribution_scheme = "novawallet"
  testflight_distribution_configuration = "Release"

  desc "Runs unit tests"
  desc "Example usage: fastlane run_unit_tests"
  lane :run_unit_tests do
    test_build(
      scheme: test_scheme,
    )
  end

  desc "Build app for CI"
  lane :build_app_ci do
    prepare_code_signing
    base_build_app(
      scheme: main_scheme,
      target: main_target,
      configuration: main_configuration
    )
  end

  desc "Distribute app to Firebase"
  desc "Parameters:"
  desc "- 'release_notes : <value>' to define release notes"
  desc " "
  desc "Example usage: fastlane distribute_app_to_firebase release_notes:'Release notes'"
  lane :distribute_app_to_firebase do |options|
    prepare_code_signing
    base_build_app(
      scheme: main_scheme,
      target: main_target,
      configuration: main_configuration
    )
    distribute_to_firebase(
      release_notes: options[:release_notes]
    )
  end

  desc "Distribute new iOS build through TestFlight"
  desc "Example usage: fastlane distribute_testflight"
  lane :distribute_testflight do
    load_asc_api_key
    prepare_code_signing
    new_build_number = latest_testflight_build_number + 1
    base_build_app(
      scheme: testflight_distribution_scheme,
      target: main_target,
      configuration:  testflight_distribution_configuration,
      build_number: new_build_number
    )
    upload_testflight(
      scheme: testflight_distribution_scheme,
      target: main_target,
      configuration:  testflight_distribution_configuration
    )
  end

  desc "Update signing data"
  desc "Example usage: fastlane update_signing"
  lane :update_signing do
    update_signing_data
  end
end
