import Foundation

protocol MultisigSignValidationWireframeProtocol: DSFeeValidationWireframeProtocol, MultisigErrorPresentable {}

final class MultisigSignValidationWireframe: MultisigSignValidationWireframeProtocol {}
