import Foundation

/// The raw values are the wire contract and must not be renamed.
public enum AnalyticsEventName: String, CaseIterable {
    case appOpened = "app_opened"
    case sessionStarted = "session_started"
    case sessionEnded = "session_ended"
    case onboardingStarted = "onboarding_started"
    case walletImportMethodSelected = "wallet_import_method_selected"
    case walletCreationStarted = "wallet_creation_started"
    case walletCreationCompleted = "wallet_creation_completed"
    case walletCreationAbandoned = "wallet_creation_abandoned"
    case featureOpened = "feature_opened"
    case swapScreenOpened = "swap_screen_opened"
    case swapInitiated = "swap_initiated"
    case swapConfirmed = "swap_confirmed"
    case swapCompleted = "swap_completed"
    case swapFailed = "swap_failed"
    case swapAbandoned = "swap_abandoned"
    case stakingFlowOpened = "staking_flow_opened"
    case stakingTypeSelected = "staking_type_selected"
    case stakingInitiated = "staking_initiated"
    case stakingConfirmed = "staking_confirmed"
    case stakingCompleted = "staking_completed"
    case stakingFailed = "staking_failed"
    case stakingAbandoned = "staking_abandoned"
    case unstakeInitiated = "unstake_initiated"
    case unstakeCompleted = "unstake_completed"
    case unstakeFailed = "unstake_failed"
    case sendInitiated = "send_initiated"
    case sendCompleted = "send_completed"
    case sendFailed = "send_failed"
    case dappOpened = "dapp_opened"
    case governanceVoteCast = "governance_vote_cast"
    case tabSwitched = "tab_switched"
    case buyInitiated = "buy_initiated"
    case buyCompleted = "buy_completed"
    case sellInitiated = "sell_initiated"
    case sellCompleted = "sell_completed"
    case bannerClicked = "banner_clicked"
    case novaCardOpened = "nova_card_opened"
    case nftSectionOpened = "nft_section_opened"
    case signRequestShown = "sign_request_shown"
    case signApproved = "sign_approved"
    case signRejected = "sign_rejected"
    case signFailed = "sign_failed"
}
