import Foundation

protocol SwipeGovVotingConfirmViewProtocol: BaseReferendumVoteConfirmViewProtocol {
    func didReceive(referendaCount: Int)
}

protocol SwipeGovVotingConfirmPresenterProtocol: BaseReferendumVoteConfirmPresenterProtocol {}

protocol SwipeGovVotingConfirmInteractorInputProtocol: ReferendumVoteConfirmInteractorInputProtocol {}

protocol SwipeGovVotingConfirmInteractorOutputProtocol: BaseReferendumVoteConfirmInteractorOutputProtocol {}

protocol SwipeGovVotingConfirmWireframeProtocol: BaseReferendumVoteConfirmWireframeProtocol {}
