import Foundation
import SoraFoundation
import SubstrateSdk

final class SwipeGovVotingConfirmInteractor: ReferendumVoteConfirmInteractor {}

extension SwipeGovVotingConfirmInteractor: SwipeGovVotingConfirmInteractorInputProtocol {}
