name: Slash Command Dispatch
on:
  pull_request_review_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT_FOR_DISPATCH }}
          commands: test
          repository: nova-wallet/slash-command-dispatch-processor
