name: Distribute TestFlight Build

concurrency:
  group: "testflight-build"
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver version number, if not provided, version will be taken from the last tag and bump build version'
        required: false
  pull_request:


env:
  XCODE_VERSION: '16.4'
  IOS_APP_VERSION: ${{ secrets.IOS_APP_VERSION }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  distribute_testflight:
    runs-on: macos-15
    name: Distribute TestFlight Build
    if: github.actor == 'stepanLav'

    steps:
    - uses: actions/checkout@v4

    - name: Setup iOS Environment
      uses: ./.github/actions/install
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
        scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
        scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
        scw_default_project_id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        scw_default_organization_id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

    - name: Push Notifications Setup
      env:
        GOOGLE_SERVICE_INFO: ${{ env.GOOGLE_SERVICE_FILE_CONTENT }}
      run: |
        GOOGLE_SERVICE_PATH=./novawallet/GoogleService-Info-Release.plist

        echo "$GOOGLE_SERVICE_INFO" > $GOOGLE_SERVICE_PATH

    - name: Set version from input
      if: ${{ inputs.version }}
      run: |
        echo "IOS_APP_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

    - name: Distribute TestFlight build
      run: bundle exec fastlane distribute_testflight
